version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
        - "-ST1006"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-SA1012"
        - "-SA1019"
        - "-SA1029"
  exclusions:
    rules:
      - linters: ["errcheck"]
        source: "^\\s*defer\\s+"
