version: "3.0"

services:
  developer-tpp:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: apps/developer-tpp/Dockerfile
  financroo-tpp:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: apps/financroo-tpp/Dockerfile
  consent-page:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: consent/consent-page/Dockerfile
  consent-self-service-portal:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: consent/self-service-portal/Dockerfile
  consent-admin-portal:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: consent/admin-portal/Dockerfile
  bank:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
  configuration:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: apps/configuration/Dockerfile
