################################################################################
# Add the following to your hosts file, eg C:\Windows\System32\drivers\etc\hosts
#
# 127.0.0.1 mock-data-holder
# 127.0.0.1 mock-data-recipient
# 127.0.0.1 mock-register
#
# Then flush the DNS cache, on Windows use: ipconfig /flushdns
################################################################################

version: '2.4'

services:
  mock-register:
    container_name: mock-register
    image: consumerdataright/mock-register
    volumes:
      - ./mount/cdr/registry-seed.json:/app/admin/Data/seed-data.json
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7005:7005"
      - "7006:7006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  mock-data-holder:
    container_name: mock-data-holder
    image: consumerdataright/mock-data-holder
    volumes:
      - ./mount/cdr/holder.json:/app/idsvr/appsettings.Production.json
      - ./mount/cdr/holder-seed.json:/app/manage/Data/seed-data.json
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  mock-data-recipient:
    container_name: mock-data-recipient
    image: docker.cloudentity.io/cdr-mock-data-recipient:0.0.1
    networks:
      default:
        aliases:
          - datarecipient.mock
    volumes:
      - ./mount/cdr/recipient.json:/app/web/appsettings.Production.json
    ports:
      - "9001:9001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production