version: "3.0"
services:
  consent-page:
    image: cloudentity/openbanking-quickstart-consent-page:${VERSION}
    container_name: consent-page
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./mount/consent-page:/data
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
    env_file:
      - .env
    environment:
      - CLIENT_ID=bukj5p6k7qdMIIDfjCCAmagAwImm5ppxxxx
      - CLIENT_SECRET=pMPBmv62z3Jt1S4sWl2qRhOhEGPVZ9EcujGL7Xy0-E0
      - ISSUER_URL=${ACP_INTERNAL_URL}/${TENANT}/system
      - CERT_FILE=/bank_cert.pem
      - KEY_FILE=/bank_key.pem
      - ROOT_CA=/ca.pem
      - BANK_URL=http://bank:8070
      - DB_FILE=/data/my.db
      - LOG_LEVEL=debug
      - SPEC=obbr
      - GIN_MODE=debug
      - DEFAULT_LANGUAGE=en-us
  bank:
    image: cloudentity/openbanking-quickstart-bank:${VERSION}
    container_name: bank
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
      - ./mount/bank:/app/data
    environment:
      - CLIENT_ID=bukj5p6k7qdmm5ppbi4g
      - ISSUER_URL=${ACP_INTERNAL_URL}/${TENANT}/openbanking
      - CERT_FILE=/bank_cert.pem
      - KEY_FILE=/bank_key.pem
      - ROOT_CA=/ca.pem
      - SPEC=obbr