version: "3.0"

services:
  financroo-tpp:
    image: cloudentity/openbanking-quickstart-financroo-tpp:${VERSION}
    container_name: financroo-tpp
    platform: linux/x86_64
    restart: always
    ports:
      - "8091:8091"
    volumes:
      - ./data:/certs
      - ./mount/financroo-tpp:/app/data
      - ./apps/financroo-tpp/banks.json:/app/banks.json
    env_file:
      - .env
    environment:
      - UI_URL=https://${APP_HOST}:8091
      - TENANT=${TENANT}
      - GIN_MODE=debug # change to release to disable gin debug
      - SPEC=generic
      - BANK_URL=http://gobank:8070
      - OPENBANKING_SERVER_ID=${SERVER}
      - ENABLE_TLS_SERVER=true
      - CLIENT_ID=${FINANCROO_TPP_CLIENT_ID}
      - ENABLE_DCR=true
      - BANKS_CONFIG_FILE=/app/banks.json
    depends_on:
      configuration:
        condition: service_completed_successfully

  gobank-consent-page:
    image: cloudentity/openbanking-quickstart-consent-page:${VERSION}
    container_name: gobank-consent-page
    platform: linux/x86_64
    restart: always
    ports:
      - "7080:8080"
    volumes:
      - ./mount/consent-page:/data
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
      - ./data/consent_storage_cert.pem:/consent_storage_cert.pem
      - ./data/consent_storage_key.pem:/consent_storage_key.pem
    env_file:
      - .env
    environment:
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/system
      - BANK_URL=http://gobank:8070
      - BANK_ACCOUNTS_ENDPOINT=http://gobank:8070/internal/accounts
      - BANK_CLIENT_TOKEN_URL=${ACP_URL}/${TENANT}/${SERVER}/oauth2/token
      - BANK_CLIENT_ID=${INTERNAL_BANK_CLIENT_ID}
      - BANK_CLIENT_SECRET=pMPBmv62z3Jt1S4sWl2qRhOhEGPVZ9EcujGL7Xy0-E0
      - LOG_LEVEL=debug
      - SPEC=generic
      - GIN_MODE=debug # change to release to disable gin debug
      - OTP_MODE=mock # change to custom to enable custom OTP handling
      - MFA_CLAIM=sub # for mobile use mobile_verified
      - CLIENT_ID=${CONSENT_PAGE_CLIENT_ID}
      - CONSENT_STORAGE_MODE=external
      - EXTERNAL_CONSENT_STORAGE_URL=https://gobank-consent-storage:8084
      - EXTERNAL_CONSENT_STORAGE_CLIENT_CERT_FILE=/consent_storage_cert.pem
      - EXTERNAL_CONSENT_STORAGE_CLIENT_KEY_FILE=/consent_storage_key.pem
      - EXTERNAL_CONSENT_STORAGE_CLIENT_ROOT_CA=/ca.pem
    depends_on:
      configuration:
        condition: service_completed_successfully

  gobank-consent-storage:
    image: openbanking-quickstart_consent-storage:${VERSION}
    container_name: gobank-consent-storage
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/system
      - SERVER=${SERVER}
      - CLIENT_ID=${CONSENT_STORAGE_CLIENT_ID}
      - CLIENT_SECRET=aMPBmv62z3Jt1S4sWl2qRhOhEGPVZ9EcujGL7Xy0-E1
    restart: on-failure
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/consent_storage_cert.pem:/consent_storage_cert.pem
      - ./data/consent_storage_key.pem:/consent_storage_key.pem
      - ./mount/gobank-consent-storage:/app/data
    depends_on:
      configuration:
        condition: service_completed_successfully

  hyperscale-consent-page:
    image: cloudentity/openbanking-quickstart-consent-page:${VERSION}
    container_name: hyperscale-consent-page
    platform: linux/x86_64
    restart: always
    ports:
      - "6080:8080"
    volumes:
      - ./mount/consent-page:/data
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
      - ./consent/consent-page/assets/images/hyperscalebank_logo.svg:/app/assets/images/bank_logo.svg
    env_file:
      - .env
    environment:
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/system
      - BANK_URL=http://hyperscalebank:8070
      - BANK_ACCOUNTS_ENDPOINT=http://hyperscalebank:8070/internal/accounts
      - BANK_CLIENT_TOKEN_URL=${ACP_URL}/${TENANT}/${SERVER}/oauth2/token
      - BANK_CLIENT_ID=${INTERNAL_BANK_CLIENT_ID}
      - BANK_CLIENT_SECRET=pMPBmv62z3Jt1S4sWl2qRhOhEGPVZ9EcujGL7Xy0-E0
      - LOG_LEVEL=debug
      - SPEC=generic
      - GIN_MODE=debug # change to release to disable gin debug
      - OTP_MODE=mock # change to custom to enable custom OTP handling
      - MFA_CLAIM=sub # for mobile use mobile_verified
      - CLIENT_ID=hyperscalebank-consent-page
      - CONSENT_STORAGE_MODE=identity
      - IDENTITY_POOL_CONSENT_STORAGE_ISSUER_URL=${ACP_URL}/${TENANT}/admin
      - IDENTITY_POOL_CONSENT_STORAGE_CLIENT_ID=hyperscalebank-consent-storage-mgmt
      - IDENTITY_POOL_CONSENT_STORAGE_CLIENT_SECRET=aXPBmv62z3Jt1S4sWl2qRhOhEGPVZ9EcujGL7Xy0-X3
      - IDENTITY_POOL_CONSENT_STORAGE_ROOT_CA=/ca.pem
      - IDENTITY_POOL_CONSENT_STORAGE_POOL_ID=hyperscalebank-consent-storage
    depends_on:
      configuration:
        condition: service_completed_successfully

  gobank:
    image: cloudentity/openbanking-quickstart-bank:${VERSION}
    container_name: gobank
    platform: linux/x86_64
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
      - ./mount/gobank-generic:/app/data
    environment:
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/${SERVER}
      - SPEC=generic
      - GIN_MODE=debug
      - CLIENT_ID=${BANK_CLIENT_ID}
    depends_on:
      configuration:
        condition: service_completed_successfully

  hyperscalebank:
    image: cloudentity/openbanking-quickstart-bank:${VERSION}
    container_name: hyperscalebank
    platform: linux/x86_64
    restart: always
    ports:
      - "7070:8070"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
      - ./mount/hyperscalebank-generic:/app/data
    environment:
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/hyperscalebank
      - SPEC=generic
      - GIN_MODE=debug
      - CLIENT_ID=hyperscalebank
    depends_on:
      configuration:
        condition: service_completed_successfully

  configuration:
    container_name: configuration-system
    platform: linux/x86_64
    image: cloudentity/openbanking-quickstart-configuration:latest
    restart: on-failure
    volumes:
      - ./data/tpp_cert.pem:/certs/tpp_cert.pem
      - ./data/ca.pem:/certs/ca.pem
      - ./data/variables.yaml:/variables.yaml
      - ./data/imports/generic/system.tmpl:/app/imports-generic/system.tmpl
      - ./data/imports/generic/gobank.tmpl:/app/imports-generic/gobank.tmpl
      - ./data/imports/generic/hyperscalebank.tmpl:/app/imports-generic/hyperscalebank.tmpl
      - ./data/imports/generic/tenant.tmpl:/app/imports-generic/tenant.tmpl
    command:
      - /app/main
      - --tenant-url
      - ${CONFIGURATION_TENANT_URL}
      - --tenant
      - ${CONFIGURATION_TENANT}
      - --client-id
      - ${CONFIGURATION_CLIENT_ID}
      - --client-secret
      - ${CONFIGURATION_CLIENT_SECRET}
      - --templates-dirs
      - /app/imports-generic
      - --variables-file
      - /variables.yaml
      - --verbose

  configuration-identity:
    container_name: configuration-identity
    platform: linux/x86_64
    image: cloudentity/openbanking-quickstart-configuration:latest
    restart: on-failure
    volumes:
      - ./data/variables.yaml:/variables.yaml
      - ./data/imports/generic/hyperscalebank-identity.tmpl:/app/imports-generic/hyperscalebank-identity.tmpl
    command:
      - /app/main
      - --tenant-url
      - ${IDENTITY_CONFIGURATION_TENANT_URL}
      - --tenant
      - ${IDENTITY_CONFIGURATION_TENANT}
      - --client-id
      - ${IDENTITY_CONFIGURATION_CLIENT_ID}
      - --client-secret
      - ${IDENTITY_CONFIGURATION_CLIENT_SECRET}
      - --templates-dirs
      - /app/imports-generic
      - --variables-file
      - /variables.yaml
      - --verbose
      - --target
      - identity
    depends_on:
      configuration:
        condition: service_completed_successfully
