version: "3.0"

services:
  developer-tpp:
    image: cloudentity/openbanking-quickstart-developer-tpp:${VERSION}
    container_name: developer-tpp
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/tpp_cert.pem:/tpp_cert.pem
      - ./data/tpp_key.pem:/tpp_key.pem
    environment:
      - CLIENT_ID=bugkgm23g9kregtu051g
      - AUTHORIZE_URL=${ACP_URL}/${TENANT}/openbanking/oauth2/authorize
      - TOKEN_URL=${ACP_MTLS_URL}/${TENANT}/openbanking/oauth2/token
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/openbanking
      - USERINFO_URL=${ACP_MTLS_URL}/${TENANT}/openbanking/userinfo
      - REDIRECT_URL=https://${APP_HOST}:8090/callback
      - CERT_FILE=/tpp_cert.pem
      - KEY_FILE=/tpp_key.pem
      - ROOT_CA=/ca.pem
      - BANK_URL=http://bank:8070
      - SPEC=obuk
    depends_on:
      configuration:
        condition: service_completed_successfully

  financroo-tpp:
    image: cloudentity/openbanking-quickstart-financroo-tpp:${VERSION}
    container_name: financroo-tpp
    restart: always
    ports:
      - "8091:8091"
    volumes:
      - ./data:/certs
      - ./mount/financroo-tpp:/app/data
    env_file:
      - .env
    environment:
      - UI_URL=https://${APP_HOST}:8091
      - CERT_FILE=/certs/tpp_cert.pem
      - KEY_FILE=/certs/tpp_key.pem
      - DB_FILE=/app/data/my.db
      - TENANT=${TENANT}
      - GIN_MODE=debug # change to release to disable gin debug
      - SPEC=obuk
      - BANK_URL=http://bank:8070
      - CLIENT_ID=bugkgm23g9kregtu051g
      - ROOT_CA=/certs/ca.pem
      - OPENBANKING_SERVER_ID=openbanking
    depends_on:
      configuration:
        condition: service_completed_successfully


  consent-page:
    image: cloudentity/openbanking-quickstart-consent-page:${VERSION}
    container_name: consent-page
    restart: always
    ports:
      - "7080:8080"
    volumes:
      - ./mount/consent-page-uk:/data
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
    env_file:
      - .env
    environment:
      - CLIENT_ID=bv0ocudfotn6edhsiu7g
      - CLIENT_SECRET=pMPBmv62z3Jt1S4sWl2qRhOhEGPVZ9EcujGL7Xy0-E0
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/system
      - CERT_FILE=/bank_cert.pem
      - KEY_FILE=/bank_key.pem
      - ROOT_CA=/ca.pem
      - BANK_URL=http://bank:8070
      - DB_FILE=/data/my.db
      - LOG_LEVEL=debug
      - SPEC=obuk
      - GIN_MODE=debug # change to release to disable gin debug
      - OTP_MODE=mock # change to custom to enable custom OTP handling
      - MFA_CLAIM=sub # for mobile use mobile_verified
      - DEFAULT_LANGUAGE=en-us
    depends_on:
      configuration:
        condition: service_completed_successfully


  consent-self-service-portal:
    image: cloudentity/openbanking-quickstart-consent-self-service-portal:${VERSION}
    container_name: consent-self-service-portal
    restart: always
    ports:
      - "8085:8085"
    env_file:
      - .env
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
    environment:
      - SYSTEM_CLIENT_ID=buc3b1hhuc714r78env0
      - SYSTEM_CLIENT_SECRET=PBV7q0akoP603rZbU0EFdxbhZ-djxF7FIVwyKaLnBYU
      - SYSTEM_ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/system
      - BANK_URL=http://bank:8070
      - CERT_FILE=/bank_cert.pem
      - KEY_FILE=/bank_key.pem
      - ROOT_CA=/ca.pem
      - LOGIN_AUTHORIZATION_SERVER_URL=${ACP_URL}
      - LOGIN_AUTHORIZATION_SERVER_ID=bank-customers
      - LOGIN_TENANT_ID=${TENANT}
      - LOGIN_CLIENT_ID=bv0nab0mekk67nekvq7g
      - INTROSPECT_CLIENT_ID=bv2dkff8mll9cf6pvd6g
      - INTROSPECT_CLIENT_SECRET=KThGH68f-gMC4cscGLFeOpIU4EYriYhKspOV9IwHbnw
      - INTROSPECT_ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/bank-customers
      - OPENBANKING_SERVER_ID=openbanking
      - SPEC=obuk
    depends_on:
      configuration:
        condition: service_completed_successfully

  consent-admin-portal:
    image: cloudentity/openbanking-quickstart-consent-admin-portal:${VERSION}
    container_name: consent-admin-portal
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
    environment:
      - SYSTEM_CLIENT_ID=bv2fe0tpfc67lmeti340
      - SYSTEM_CLIENT_SECRET=v6yYaApda9juR_DrlI5mpdsdm9u2-D0rQIG9ynakyDE
      - SYSTEM_ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/system
      - SYSTEM_CLIENTS_SERVER_ID=openbanking
      - CERT_FILE=/bank_cert.pem
      - KEY_FILE=/bank_key.pem
      - ROOT_CA=/ca.pem
      - OPENBANKING_UK_WORKSPACE_ID=openbanking
      - OPENBANKING_BRASIL_WORKSPACE_ID=openbanking_brasil
      - CDR_WORKSPACE_ID=cdr
      - INTROSPECT_CLIENT_ID=bv2fddlpfc67lmeti32g
      - INTROSPECT_CLIENT_SECRET=RkAIOVRlP6ZLhDvYixT1wBb8DG3bVkXAouoIrX7cwzA
      - INTROSPECT_ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/bank-admins
    depends_on:
      configuration:
        condition: service_completed_successfully

  bank:
    image: cloudentity/openbanking-quickstart-bank:${VERSION}
    container_name: bank
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./data/ca.pem:/ca.pem
      - ./data/bank_cert.pem:/bank_cert.pem
      - ./data/bank_key.pem:/bank_key.pem
      - ./mount/bank-uk:/app/data
    environment:
      - CLIENT_ID=bukj5p6k7qdmm5ppbi4g
      - ISSUER_URL=${ACP_MTLS_URL}/${TENANT}/openbanking
      - CERT_FILE=/bank_cert.pem
      - KEY_FILE=/bank_key.pem
      - ROOT_CA=/ca.pem
      - SPEC=obuk
      - GIN_MODE=debug
    depends_on:
      configuration:
        condition: service_completed_successfully

  configuration:
    container_name: configuration
    image: cloudentity/openbanking-quickstart-configuration:latest
    restart: on-failure
    volumes:
      - ./data/tpp_cert.pem:/certs/tpp_cert.pem
      - ./data/ca.pem:/certs/ca.pem
      - ./data/variables.yaml:/variables.yaml
      - ./data/imports/system.tmpl:/app/imports-obuk/system.tmpl
      - ./data/imports/bank-customers.tmpl:/app/imports-obuk/bank-customers.tmpl
      - ./data/imports/openbanking-uk.tmpl:/app/imports-obuk/openbanking-uk.tmpl
    command:
      - /app/main
      - --tenant-url
      - ${CONFIGURATION_TENANT_URL}
      - --tenant
      - ${CONFIGURATION_TENANT}
      - --client-id
      - ${CONFIGURATION_CLIENT_ID}
      - --client-secret
      - ${CONFIGURATION_CLIENT_SECRET}
      - --templates-dirs
      - /app/imports-obuk
      - --variables-file
      - /variables.yaml
      - --verbose   

