version: "3.0"
services:
  mongodb:
    image: mongo:4.2
    volumes:
      - ./conformance/mongo/data:/data/db
  httpd:
    image: certification_httpd
    ports:
      - "443:8443"
    depends_on:
      - server
  server:
    image: certification_server
    command: >
      java
      -jar /server/fapi-test-suite.jar
      --fintechlabs.base_url=https://fapi-test:443
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
