name: cypress-branch

on:
  push:
    branches-ignore:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.cloudentity.io
          username: ${{ secrets.PUBLIC_DOCKER_CLOUDENTITY_REPO_DEV_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_CLOUDENTITY_REPO_DEV_PASSWORD }}

      - name: Add authorization.cloudentity.com to hosts
        run: echo "127.0.0.1       authorization.cloudentity.com" | sudo tee -a /etc/hosts

      - name: Add test-docker to hosts
        run: echo "127.0.0.1       test-docker" | sudo tee -a /etc/hosts

      - name: Check hosts
        run: cat /etc/hosts

      - name: Make build
        run: make build

      - name: Docker stats
        run: |
          nohup docker stats --no-trunc > stats 2>&1 &
          echo $! > save_pid.txt

      - name: Make run with disabled mfa
        run: make disable-mfa run

      - name: Run cypress tests without mfa
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump stats
        if: failure()
        run: |
          cat stats
          kill -9 `cat save_pid.txt`

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: Make with enabled mfa
        run: make enable-mfa run

      - name: Run cypress tests with mfa
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: clean
        run: make clean

      - name: Make run with OBBR environment
        run: make enable-spec-obbr run
      
      - name: Run cypress tests with OBBR environment
        uses: cypress-io/github-action@v2
        with: 
          working-directory: tests
          spec: cypress/integration/TppTechnicalTests.ts

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: tests/cypress/videos

      - name: clean
        run: make clean

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: tests/cypress/videos
