name: cypress-branch

on:
  push:
    branches-ignore:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker-public.artifactory.cloudentity.com
          username: ${{ secrets.PUBLIC_DOCKER_CLOUDENTITY_REPO_DEV_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_CLOUDENTITY_REPO_DEV_PASSWORD }}

      - name: Add authorization.cloudentity.com to hosts
        run: sudo echo "127.0.0.1       authorization.cloudentity.com" >> /etc/hosts

      - name: Install deps
        run: apt update && apt install -y make curl &&  curl -fsSL https://get.docker.com -o get-docker.sh | sh && groupadd docker && newgrp docker && curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

      - name: Make build
        run: make build
            
      - name: Make run with disabled mfa
        run: make disable-mfa run

      - name: Run cypress tests without mfa
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests

      - name: Make with enabled mfa
        run: make enable-mfa run

      - name: Run cypress tests with mfa
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests

      - name: clean
        run: make clean

      - name: Make run with OBBR environment
        run: make enable-spec-obbr run
      
      - name: Run cypress tests with OBBR environment
        uses: cypress-io/github-action@v2
        with: 
          working-directory: tests
          spec: cypress/integration/TppTechnicalTests.ts

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: tests/cypress/videos

      - name: clean
        run: make clean

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: tests/cypress/videos
