name: docker

on:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - folder: "apps/financroo-tpp"
            suffix: "financroo-tpp"
          - folder: "apps/developer-tpp"
            suffix: "developer-tpp"
          - folder: "consent/admin-portal"
            suffix: "consent-admin-portal"
          - folder: "consent/self-service-portal"
            suffix: "consent-self-service-portal"
          - folder: "consent/consent-page"
            suffix: "consent-page"
          - folder: "apps/bank"
            suffix: "bank"
          - folder: "apps/configuration"
            suffix: "configuration"

    name: Build and push docker ${{ matrix.images.suffix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set version
        run: |
          echo "VERSION=$(./scripts/version.sh)" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cloudentity/openbanking-quickstart-${{ matrix.images.suffix }}:${{ env.VERSION }}
          context: .
          file: ./${{ matrix.images.folder }}/Dockerfile
