name: pipeline

on:
  push:
  pull_request:
    types: [opened]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: go setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5

    - name: lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.43.0
        skip-go-installation: true
