name: bump acp image
on:
  repository_dispatch:
    types: [bump-acp-image]

jobs:
  update_repo:
    name: Update ACP image
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: master
          fetch-depth: 0

      - name: Update ACP image
        run: ./scripts/override_env.sh ACP_VERSION ${{ github.event.client_payload.acp-version }} 

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: Github automation
          author_email: mail@example.com
          message: 'Bump ACP image'
          add: '.env-local'
          new_branch: bump-acp-image-${{ steps.date.outputs.date }}

      - name: Create PR
        uses: devops-infra/action-pull-request@d2b6e10c00db8cf882070717497bfcebe0414e18 # v0.5.3
        with:
          source_branch: bump-acp-image-${{ steps.date.outputs.date }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Bump ACP image
          body: "**Automated pull request**"
          draft: false
          allow_no_diff: false

      - name: Auto-approve PR
        env:
          GH_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_DEVOPS_2_PAT1 }}
        run: gh pr review --approve bump-acp-image-${{ steps.date.outputs.date }}

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_DEVOPS_2_PAT1 }}
        run: gh pr merge --auto --squash bump-acp-image-${{ steps.date.outputs.date }}